
# Header
menu:
  主页: http://ruantao1989.github.io
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "#"
  weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
#google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars2.githubusercontent.com/u/1949437?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: '这辈子就俩爱好: 一是写程序 二是摄影.
毕业时候选了第一个爱好谋生, 从此也少有机会 直接发挥我在第二个爱好上的天赋...

毕业3年来 迫于生计写过c, java, js但无一精通. 正所谓不会写存储过程的javaer不是好前端...
作为一只老菜鸟, 不太想定义自己是个XX语言的程序猿, 更希望通过所学 去更好的解决问题.

走好眼前最近的一步固然重要, 但很多东西 就像是取景器里的焦点: 只有你先去主动的选择和专注, 才出现你所设想的效果.
所以目前和未来一段时间里, 我会集中精力专注于用js解决工作中的问题.

GitHub地址: https://github.com/ruantao1989
Lofter地址 : http://ruantao1989.lofter.com'